/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);

import MainButton from '@components/ui/MainButton'
import React, { useEffect, useState } from 'react'
import moment from 'jalali-moment'
import TimeTable from '@components/TableComponents/weekly'
import { useMediaQuery } from 'react-responsive'
import { useTableContext } from 'src/context/useTableContext'
import styles from './styles.module.scss'

function WeeklyContainer() {
  const [currentDate, setCurrentDate] = useState('')
     const {
       showDay,
       endDay,
       scheduleData,
       weeklyMutaition,
       sunDay,
       monDay,
       tuesDay,
       wednesDay,
       thursDay,
     } = useTableContext()

  const sunData = [
    {
      id: 1,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T06:00:00'),
      endTime: new Date(sunDay + 'T06:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 2,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T06:30:00'),
      endTime: new Date(sunDay + 'T07:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 3,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T07:00:00'),
      endTime: new Date(sunDay + 'T07:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 4,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T07:30:00'),
      endTime: new Date(sunDay + 'T08:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 5,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T08:00:00'),
      endTime: new Date(sunDay + 'T08:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 6,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T08:30:00'),
      endTime: new Date(sunDay + 'T09:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 7,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T09:00:00'),
      endTime: new Date(sunDay + 'T09:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 8,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T09:30:00'),
      endTime: new Date(sunDay + 'T10:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 9,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T10:00:00'),
      endTime: new Date(sunDay + 'T10:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 10,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T10:30:00'),
      endTime: new Date(sunDay + 'T11:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 11,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T11:00:00'),
      endTime: new Date(sunDay + 'T11:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 12,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T11:30:00'),
      endTime: new Date(sunDay + 'T12:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 13,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T12:00:00'),
      endTime: new Date(sunDay + 'T12:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 14,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T12:30:00'),
      endTime: new Date(sunDay + 'T13:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 15,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T13:00:00'),
      endTime: new Date(sunDay + 'T13:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 16,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T13:30:00'),
      endTime: new Date(sunDay + 'T14:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 17,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T14:00:00'),
      endTime: new Date(sunDay + 'T14:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 18,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T14:30:00'),
      endTime: new Date(sunDay + 'T15:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 19,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T15:00:00'),
      endTime: new Date(sunDay + 'T15:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 20,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T15:30:00'),
      endTime: new Date(sunDay + 'T16:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 21,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T16:00:00'),
      endTime: new Date(sunDay + 'T16:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 22,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T16:30:00'),
      endTime: new Date(showDay + 'T17:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 23,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T17:00:00'),
      endTime: new Date(sunDay + 'T17:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 24,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T17:30:00'),
      endTime: new Date(sunDay + 'T18:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 25,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T18:00:00'),
      endTime: new Date(sunDay + 'T18:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 26,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T18:30:00'),
      endTime: new Date(sunDay + 'T19:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 27,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T19:00:00'),
      endTime: new Date(sunDay + 'T19:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 28,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T19:30:00'),
      endTime: new Date(sunDay + 'T20:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 29,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T20:00:00'),
      endTime: new Date(sunDay + 'T20:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 30,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T20:30:00'),
      endTime: new Date(sunDay + 'T21:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 31,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T21:00:00'),
      endTime: new Date(sunDay + 'T21:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 32,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T21:30:00'),
      endTime: new Date(showDay + 'T22:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 33,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T22:00:00'),
      endTime: new Date(sunDay + 'T22:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 34,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T22:30:00'),
      endTime: new Date(sunDay + 'T23:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 35,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T23:00:00'),
      endTime: new Date(sunDay + 'T23:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 36,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(sunDay + 'T23:30:00'),
      endTime: new Date(sunDay + 'T00:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
  ]
  const satData = [
    {
      id: 1,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T06:00:00'),
      endTime: new Date(showDay + 'T06:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 2,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T06:30:00'),
      endTime: new Date(showDay + 'T07:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 3,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T07:00:00'),
      endTime: new Date(showDay + 'T07:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 4,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T07:30:00'),
      endTime: new Date(showDay + 'T08:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 5,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T08:00:00'),
      endTime: new Date(showDay + 'T08:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 6,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T08:30:00'),
      endTime: new Date(showDay + 'T09:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 7,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T09:00:00'),
      endTime: new Date(showDay + 'T09:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 8,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T09:30:00'),
      endTime: new Date(showDay + 'T10:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 9,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T10:00:00'),
      endTime: new Date(showDay + 'T10:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 10,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T10:30:00'),
      endTime: new Date(showDay + 'T11:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 11,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T11:00:00'),
      endTime: new Date(showDay + 'T11:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 12,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T11:30:00'),
      endTime: new Date(showDay + 'T12:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 13,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T12:00:00'),
      endTime: new Date(showDay + 'T12:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 14,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T12:30:00'),
      endTime: new Date(showDay + 'T13:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 15,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T13:00:00'),
      endTime: new Date(showDay + 'T13:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 16,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T13:30:00'),
      endTime: new Date(showDay + 'T14:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 17,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T14:00:00'),
      endTime: new Date(showDay + 'T14:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 18,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T14:30:00'),
      endTime: new Date(showDay + 'T15:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 19,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T15:00:00'),
      endTime: new Date(showDay + 'T15:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 20,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T15:30:00'),
      endTime: new Date(showDay + 'T16:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 21,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T16:00:00'),
      endTime: new Date(showDay + 'T16:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 22,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T16:30:00'),
      endTime: new Date(showDay + 'T17:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 23,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T17:00:00'),
      endTime: new Date(showDay + 'T17:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 24,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T17:30:00'),
      endTime: new Date(showDay + 'T18:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 25,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T18:00:00'),
      endTime: new Date(showDay + 'T18:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 26,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T18:30:00'),
      endTime: new Date(showDay + 'T19:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 27,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T19:00:00'),
      endTime: new Date(showDay + 'T19:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 28,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T19:30:00'),
      endTime: new Date(showDay + 'T20:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 29,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T20:00:00'),
      endTime: new Date(showDay + 'T20:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 30,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T20:30:00'),
      endTime: new Date(showDay + 'T21:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 31,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T21:00:00'),
      endTime: new Date(showDay + 'T21:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 32,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T21:30:00'),
      endTime: new Date(showDay + 'T22:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 33,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T22:00:00'),
      endTime: new Date(showDay + 'T22:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 34,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T22:30:00'),
      endTime: new Date(showDay + 'T23:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 35,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T23:00:00'),
      endTime: new Date(showDay + 'T23:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 36,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T23:30:00'),
      endTime: new Date(showDay + 'T00:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
  ]
  const monData = [
    {
      id: 1,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T06:00:00'),
      endTime: new Date(monDay + 'T06:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 2,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T06:30:00'),
      endTime: new Date(monDay + 'T07:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 3,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T07:00:00'),
      endTime: new Date(monDay + 'T07:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 4,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T07:30:00'),
      endTime: new Date(monDay + 'T08:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 5,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T08:00:00'),
      endTime: new Date(monDay + 'T08:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 6,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T08:30:00'),
      endTime: new Date(monDay + 'T09:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 7,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T09:00:00'),
      endTime: new Date(monDay + 'T09:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 8,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T09:30:00'),
      endTime: new Date(monDay + 'T10:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 9,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T10:00:00'),
      endTime: new Date(monDay + 'T10:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 10,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T10:30:00'),
      endTime: new Date(monDay + 'T11:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 11,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T11:00:00'),
      endTime: new Date(monDay + 'T11:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 12,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T11:30:00'),
      endTime: new Date(monDay + 'T12:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 13,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T12:00:00'),
      endTime: new Date(monDay + 'T12:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 14,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T12:30:00'),
      endTime: new Date(monDay + 'T13:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 15,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T13:00:00'),
      endTime: new Date(monDay + 'T13:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 16,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T13:30:00'),
      endTime: new Date(monDay + 'T14:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 17,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T14:00:00'),
      endTime: new Date(monDay + 'T14:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 18,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T14:30:00'),
      endTime: new Date(monDay + 'T15:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 19,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T15:00:00'),
      endTime: new Date(monDay + 'T15:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 20,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T15:30:00'),
      endTime: new Date(monDay + 'T16:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 21,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T16:00:00'),
      endTime: new Date(monDay + 'T16:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 22,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T16:30:00'),
      endTime: new Date(monDay + 'T17:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 23,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T17:00:00'),
      endTime: new Date(monDay + 'T17:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 24,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T17:30:00'),
      endTime: new Date(monDay + 'T18:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 25,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T18:00:00'),
      endTime: new Date(monDay + 'T18:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 26,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T18:30:00'),
      endTime: new Date(monDay + 'T19:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 27,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(showDay + 'T19:00:00'),
      endTime: new Date(showDay + 'T19:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 28,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T19:30:00'),
      endTime: new Date(monDay + 'T20:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 29,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T20:00:00'),
      endTime: new Date(monDay + 'T20:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 30,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T20:30:00'),
      endTime: new Date(monDay + 'T21:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 31,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T21:00:00'),
      endTime: new Date(monDay + 'T21:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 32,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T21:30:00'),
      endTime: new Date(monDay + 'T22:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 33,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T22:00:00'),
      endTime: new Date(monDay + 'T22:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 34,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T22:30:00'),
      endTime: new Date(monDay + 'T23:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 35,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T23:00:00'),
      endTime: new Date(monDay + 'T23:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 36,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(monDay + 'T23:30:00'),
      endTime: new Date(monDay + 'T00:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
  ]
  const tueData = [
    {
      id: 1,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T06:00:00'),
      endTime: new Date(tuesDay + 'T06:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 2,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T06:30:00'),
      endTime: new Date(tuesDay + 'T07:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 3,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T07:00:00'),
      endTime: new Date(tuesDay + 'T07:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 4,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T07:30:00'),
      endTime: new Date(tuesDay + 'T08:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 5,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T08:00:00'),
      endTime: new Date(tuesDay + 'T08:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 6,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T08:30:00'),
      endTime: new Date(tuesDay + 'T09:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 7,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T09:00:00'),
      endTime: new Date(tuesDay + 'T09:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 8,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T09:30:00'),
      endTime: new Date(tuesDay + 'T10:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 9,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T10:00:00'),
      endTime: new Date(tuesDay + 'T10:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 10,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T10:30:00'),
      endTime: new Date(tuesDay + 'T11:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 11,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T11:00:00'),
      endTime: new Date(tuesDay + 'T11:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 12,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T11:30:00'),
      endTime: new Date(tuesDay + 'T12:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 13,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T12:00:00'),
      endTime: new Date(tuesDay + 'T12:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 14,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T12:30:00'),
      endTime: new Date(tuesDay + 'T13:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 15,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T13:00:00'),
      endTime: new Date(tuesDay + 'T13:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 16,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T13:30:00'),
      endTime: new Date(tuesDay + 'T14:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 17,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T14:00:00'),
      endTime: new Date(tuesDay + 'T14:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 18,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T14:30:00'),
      endTime: new Date(tuesDay + 'T15:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 19,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T15:00:00'),
      endTime: new Date(tuesDay + 'T15:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 20,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T15:30:00'),
      endTime: new Date(tuesDay + 'T16:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 21,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T16:00:00'),
      endTime: new Date(tuesDay + 'T16:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 22,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T16:30:00'),
      endTime: new Date(tuesDay + 'T17:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 23,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T17:00:00'),
      endTime: new Date(tuesDay + 'T17:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 24,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T17:30:00'),
      endTime: new Date(tuesDay + 'T18:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 25,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T18:00:00'),
      endTime: new Date(tuesDay + 'T18:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 26,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T18:30:00'),
      endTime: new Date(tuesDay + 'T19:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 27,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T19:00:00'),
      endTime: new Date(tuesDay + 'T19:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 28,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T19:30:00'),
      endTime: new Date(tuesDay + 'T20:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 29,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T20:00:00'),
      endTime: new Date(tuesDay + 'T20:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 30,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T20:30:00'),
      endTime: new Date(tuesDay + 'T21:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 31,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T21:00:00'),
      endTime: new Date(tuesDay + 'T21:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 32,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T21:30:00'),
      endTime: new Date(tuesDay + 'T22:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 33,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T22:00:00'),
      endTime: new Date(tuesDay + 'T22:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 34,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T22:30:00'),
      endTime: new Date(tuesDay + 'T23:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 35,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T23:00:00'),
      endTime: new Date(tuesDay + 'T23:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 36,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(tuesDay + 'T23:30:00'),
      endTime: new Date(tuesDay + 'T00:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
  ]
  const wedData = [
    {
      id: 1,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T06:00:00'),
      endTime: new Date(wednesDay + 'T06:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 2,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T06:30:00'),
      endTime: new Date(wednesDay + 'T07:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 3,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T07:00:00'),
      endTime: new Date(wednesDay + 'T07:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 4,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T07:30:00'),
      endTime: new Date(wednesDay + 'T08:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 5,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T08:00:00'),
      endTime: new Date(wednesDay + 'T08:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 6,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T08:30:00'),
      endTime: new Date(wednesDay + 'T09:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 7,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T09:00:00'),
      endTime: new Date(wednesDay + 'T09:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 8,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T09:30:00'),
      endTime: new Date(wednesDay + 'T10:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 9,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T10:00:00'),
      endTime: new Date(wednesDay + 'T10:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 10,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T10:30:00'),
      endTime: new Date(wednesDay + 'T11:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 11,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T11:00:00'),
      endTime: new Date(wednesDay + 'T11:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 12,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T11:30:00'),
      endTime: new Date(wednesDay + 'T12:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 13,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T12:00:00'),
      endTime: new Date(wednesDay + 'T12:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 14,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T12:30:00'),
      endTime: new Date(wednesDay + 'T13:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 15,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T13:00:00'),
      endTime: new Date(wednesDay + 'T13:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 16,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T13:30:00'),
      endTime: new Date(wednesDay + 'T14:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 17,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T14:00:00'),
      endTime: new Date(wednesDay + 'T14:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 18,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T14:30:00'),
      endTime: new Date(wednesDay + 'T15:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 19,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T15:00:00'),
      endTime: new Date(wednesDay + 'T15:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 20,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T15:30:00'),
      endTime: new Date(wednesDay + 'T16:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 21,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T16:00:00'),
      endTime: new Date(wednesDay + 'T16:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 22,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T16:30:00'),
      endTime: new Date(wednesDay + 'T17:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 23,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T17:00:00'),
      endTime: new Date(wednesDay + 'T17:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 24,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T17:30:00'),
      endTime: new Date(wednesDay + 'T18:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 25,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T18:00:00'),
      endTime: new Date(wednesDay + 'T18:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 26,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T18:30:00'),
      endTime: new Date(wednesDay + 'T19:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 27,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T19:00:00'),
      endTime: new Date(wednesDay + 'T19:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 28,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T19:30:00'),
      endTime: new Date(wednesDay + 'T20:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 29,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T20:00:00'),
      endTime: new Date(wednesDay + 'T20:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 30,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T20:30:00'),
      endTime: new Date(wednesDay + 'T21:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 31,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T21:00:00'),
      endTime: new Date(wednesDay + 'T21:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 32,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T21:30:00'),
      endTime: new Date(wednesDay + 'T22:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 33,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T22:00:00'),
      endTime: new Date(wednesDay + 'T22:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 34,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T22:30:00'),
      endTime: new Date(wednesDay + 'T23:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 35,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T23:00:00'),
      endTime: new Date(wednesDay + 'T23:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 36,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(wednesDay + 'T23:30:00'),
      endTime: new Date(wednesDay + 'T00:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
  ]
  const thuData = [
    {
      id: 1,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T06:00:00'),
      endTime: new Date(thursDay + 'T06:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 2,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T06:30:00'),
      endTime: new Date(thursDay + 'T07:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 3,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T07:00:00'),
      endTime: new Date(thursDay + 'T07:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 4,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T07:30:00'),
      endTime: new Date(thursDay + 'T08:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 5,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T08:00:00'),
      endTime: new Date(thursDay + 'T08:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 6,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T08:30:00'),
      endTime: new Date(showDay + 'T09:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 7,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T09:00:00'),
      endTime: new Date(thursDay + 'T09:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 8,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T09:30:00'),
      endTime: new Date(thursDay + 'T10:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 9,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T10:00:00'),
      endTime: new Date(thursDay + 'T10:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 10,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T10:30:00'),
      endTime: new Date(thursDay + 'T11:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 11,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T11:00:00'),
      endTime: new Date(thursDay + 'T11:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 12,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T11:30:00'),
      endTime: new Date(thursDay + 'T12:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 13,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T12:00:00'),
      endTime: new Date(thursDay + 'T12:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 14,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T12:30:00'),
      endTime: new Date(thursDay + 'T13:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 15,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T13:00:00'),
      endTime: new Date(thursDay + 'T13:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 16,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T13:30:00'),
      endTime: new Date(thursDay + 'T14:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 17,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T14:00:00'),
      endTime: new Date(thursDay + 'T14:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 18,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T14:30:00'),
      endTime: new Date(thursDay + 'T15:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 19,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T15:00:00'),
      endTime: new Date(thursDay + 'T15:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 20,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T15:30:00'),
      endTime: new Date(thursDay + 'T16:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 21,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T16:00:00'),
      endTime: new Date(thursDay + 'T16:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 22,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T16:30:00'),
      endTime: new Date(thursDay + 'T17:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 23,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T17:00:00'),
      endTime: new Date(thursDay + 'T17:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 24,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T17:30:00'),
      endTime: new Date(thursDay + 'T18:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 25,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T18:00:00'),
      endTime: new Date(thursDay + 'T18:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 26,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T18:30:00'),
      endTime: new Date(thursDay + 'T19:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 27,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T19:00:00'),
      endTime: new Date(thursDay + 'T19:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 28,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T19:30:00'),
      endTime: new Date(thursDay + 'T20:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 29,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T20:00:00'),
      endTime: new Date(thursDay + 'T20:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 30,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T20:30:00'),
      endTime: new Date(thursDay + 'T21:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 31,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T21:00:00'),
      endTime: new Date(thursDay + 'T21:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 32,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T21:30:00'),
      endTime: new Date(thursDay + 'T22:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 33,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T22:00:00'),
      endTime: new Date(thursDay + 'T22:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 34,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T22:30:00'),
      endTime: new Date(thursDay + 'T23:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 35,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T23:00:00'),
      endTime: new Date(thursDay + 'T23:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 36,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(thursDay + 'T23:30:00'),
      endTime: new Date(thursDay + 'T00:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
  ]
  const friData = [
    {
      id: 1,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T06:00:00'),
      endTime: new Date(endDay + 'T06:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 2,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T06:30:00'),
      endTime: new Date(endDay + 'T07:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 3,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T07:00:00'),
      endTime: new Date(endDay + 'T07:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 4,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T07:30:00'),
      endTime: new Date(endDay + 'T08:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 5,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T08:00:00'),
      endTime: new Date(endDay + 'T08:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 6,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T08:30:00'),
      endTime: new Date(endDay + 'T09:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 7,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T09:00:00'),
      endTime: new Date(endDay + 'T09:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 8,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T09:30:00'),
      endTime: new Date(endDay + 'T10:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 9,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T10:00:00'),
      endTime: new Date(endDay + 'T10:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 10,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T10:30:00'),
      endTime: new Date(endDay + 'T11:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 11,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T11:00:00'),
      endTime: new Date(endDay + 'T11:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 12,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T11:30:00'),
      endTime: new Date(endDay + 'T12:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 13,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T12:00:00'),
      endTime: new Date(endDay + 'T12:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 14,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T12:30:00'),
      endTime: new Date(endDay + 'T13:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 15,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T13:00:00'),
      endTime: new Date(endDay + 'T13:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 16,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T13:30:00'),
      endTime: new Date(endDay + 'T14:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 17,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T14:00:00'),
      endTime: new Date(endDay + 'T14:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 18,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T14:30:00'),
      endTime: new Date(endDay + 'T15:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 19,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T15:00:00'),
      endTime: new Date(endDay + 'T15:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 20,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T15:30:00'),
      endTime: new Date(endDay + 'T16:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 21,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T16:00:00'),
      endTime: new Date(endDay + 'T16:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 22,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T16:30:00'),
      endTime: new Date(endDay + 'T17:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 23,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T17:00:00'),
      endTime: new Date(endDay + 'T17:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 24,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T17:30:00'),
      endTime: new Date(endDay + 'T18:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 25,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T18:00:00'),
      endTime: new Date(endDay + 'T18:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 26,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T18:30:00'),
      endTime: new Date(endDay + 'T19:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 27,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T19:00:00'),
      endTime: new Date(endDay + 'T19:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 28,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T19:30:00'),
      endTime: new Date(endDay + 'T20:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 29,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T20:00:00'),
      endTime: new Date(endDay + 'T20:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 30,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T20:30:00'),
      endTime: new Date(endDay + 'T21:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 31,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T21:00:00'),
      endTime: new Date(endDay + 'T21:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 32,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T21:30:00'),
      endTime: new Date(endDay + 'T22:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 33,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T22:00:00'),
      endTime: new Date(endDay + 'T22:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 34,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T22:30:00'),
      endTime: new Date(endDay + 'T23:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 35,
      name: '',
      type: '',
      body_color: 'F1F1F1',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T23:00:00'),
      endTime: new Date(endDay + 'T23:30:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
    {
      id: 36,
      name: '',
      type: '',
      body_color: 'FFFFFF',
      border_color: 'E4E5EF',
      startTime: new Date(endDay + 'T23:30:00'),
      endTime: new Date(endDay + 'T00:00:00'),
      status: '',
      statusColor: '',
      puzzleValue: '',
    },
  ]
  var arr = []
  var len = scheduleData?.items?.length
  for (var i = 0; i < len; i++) {
    arr.push(scheduleData?.items[i]?.schedules)

  }

  
  var sat: {
    id: any
    name: any
    type: any
    body_color: any
    border_color: any
    startTime: Date
    endTime: Date
    status: string
    statusColor:string
    puzzleValue:any
  }[] = []
  var satleng = arr[0]?.length
  for (var i = 0; i < satleng; i++) {
    sat.push({
      id: arr[0]?.[i].slug,
      name: arr[0]?.[i].title,
      type: arr[0]?.[i].type,
      body_color: arr[0]?.[i].body_color,
      border_color: arr[0]?.[i].border_color,
      status: arr[0]?.[i].status,
      statusColor: arr[0]?.[i].border_color,
      puzzleValue: arr[0]?.[i].border_color.puzzle,
      startTime: new Date(
        arr[0]?.[i].day?.slice(0, 10) + 'T' + arr[0]?.[i].from,
      ),
      endTime: new Date(arr[0]?.[i].day?.slice(0, 10) + 'T' + arr[0]?.[i].to),
    })
  }
  var sun: {
    id: any
    name: any
    type: any
    body_color: any
    border_color: any
    startTime: Date
    endTime: Date
    status: string
    statusColor: string
    puzzleValue: any
  }[] = []
  var sunleng = arr[1]?.length
  for (var i = 0; i < sunleng; i++) {
    sun.push({
      id: arr[1]?.[i].slug,
      name: arr[1]?.[i].title,
      type: arr[1]?.[i].type,
      body_color: arr[1]?.[i].body_color,
      border_color: arr[1]?.[i].border_color,
      status: arr[1]?.[i].status,
      statusColor: arr[1]?.[i].border_color,
      puzzleValue: arr[1]?.[i].border_color.puzzle,
      startTime: new Date(
        arr[1]?.[i].day?.slice(0, 10) + 'T' + arr[1]?.[i].from,
      ),
      endTime: new Date(arr[1]?.[i].day?.slice(0, 10) + 'T' + arr[1]?.[i].to),
    })
  }

  var mon:
    | { endTime: { getMinutes: () => string } }[]
    | {
        id: any
        name: any
        type: any
        body_color: any
        border_color: any
        startTime: Date
        endTime: Date
        status: string
        statusColor: string
        puzzleValue: any
      }[] = []
  var monleng = arr[2]?.length
  for (var i = 0; i < monleng; i++) {
    mon.push({
      id: arr[2]?.[i].slug,
      name: arr[2]?.[i].title,
      type: arr[2]?.[i].type,
      body_color: arr[2]?.[i].body_color,
      border_color: arr[2]?.[i].border_color,
      status: arr[2]?.[i].status,
      statusColor: arr[2]?.[i].border_color,
      puzzleValue: arr[2]?.[i].border_color.puzzle,
      startTime: new Date(
        arr[2]?.[i].day?.slice(0, 10) + 'T' + arr[2]?.[i].from,
      ),
      endTime: new Date(arr[2]?.[i].day?.slice(0, 10) + 'T' + arr[2]?.[i].to),
    })
  }
  var tue: {
    id: any
    name: any
    type: any
    body_color: any
    border_color: any
    startTime: Date
    endTime: Date
    status: string
    statusColor: string
    puzzleValue: any
  }[] = []
  var tueleng = arr[3]?.length
  for (var i = 0; i < tueleng; i++) {
    tue.push({
      id: arr[3]?.[i].slug,
      name: arr[3]?.[i].title,
      type: arr[3]?.[i].type,
      body_color: arr[3]?.[i].body_color,
      border_color: arr[3]?.[i].border_color,
      status: arr[3]?.[i].status,
      statusColor: arr[3]?.[i].border_color,
      puzzleValue: arr[3]?.[i].border_color.puzzle,
      startTime: new Date(
        arr[3]?.[i].day?.slice(0, 10) + 'T' + arr[3]?.[i].from,
      ),
      endTime: new Date(arr[3]?.[i].day?.slice(0, 10) + 'T' + arr[3]?.[i].to),
    })
  }
  var wed: {
    id: any
    name: any
    type: any
    body_color: any
    border_color: any
    startTime: Date
    endTime: Date
    status: string
    statusColor: string
    puzzleValue: any
  }[] = []
  var wedleng = arr[4]?.length
  for (var i = 0; i < wedleng; i++) {
    wed.push({
      id: arr[4]?.[i].slug,
      name: arr[4]?.[i].title,
      type: arr[4]?.[i].type,
      body_color: arr[4]?.[i].body_color,
      border_color: arr[4]?.[i].border_color,
      status: arr[4]?.[i].status,
      statusColor: arr[4]?.[i].border_color,
      puzzleValue: arr[4]?.[i].border_color.puzzle,
      startTime: new Date(
        arr[4]?.[i].day?.slice(0, 10) + 'T' + arr[4]?.[i].from,
      ),
      endTime: new Date(arr[4]?.[i].day?.slice(0, 10) + 'T' + arr[4]?.[i].to),
    })
  }
  var thu: {
    id: any
    name: any
    type: any
    body_color: any
    border_color: any
    startTime: Date
    endTime: Date
    status: string
    statusColor: string
    puzzleValue: any
  }[] = []
  var thuleng = arr[5]?.length
  for (var i = 0; i < thuleng; i++) {
    thu.push({
      id: arr[5]?.[i].slug,
      name: arr[5]?.[i].title,
      type: arr[5]?.[i].type,
      body_color: arr[5]?.[i].body_color,
      border_color: arr[5]?.[i].border_color,
      status: arr[5]?.[i].status,
      statusColor: arr[5]?.[i].border_color,
      puzzleValue: arr[5]?.[i].border_color.puzzle,
      startTime: new Date(
        arr[5]?.[i].day?.slice(0, 10) + 'T' + arr[5]?.[i].from,
      ),
      endTime: new Date(arr[5]?.[i].day?.slice(0, 10) + 'T' + arr[5]?.[i].to),
    })
  }
  var fri: {
    id: any
    name: any
    type: any
    body_color: any
    border_color: any
    startTime: Date
    endTime: Date
    status: string
    statusColor: string
    puzzleValue: any
  }[] = []
  var frileng = arr[6]?.length
  for (var i = 0; i < frileng; i++) {
    fri.push({
      id: arr[6]?.[i].slug,
      name: arr[6]?.[i].title,
      type: arr[6]?.[i].type,
      body_color: arr[6]?.[i].body_color,
      border_color: arr[6]?.[i].border_color,
      status: arr[6]?.[i].status,
      statusColor: arr[6]?.[i].border_color,
      puzzleValue: arr[6]?.[i].border_color.puzzle,
      startTime: new Date(
        arr[6]?.[i].day?.slice(0, 10) + 'T' + arr[6]?.[i].from,
      ),
      endTime: new Date(arr[6]?.[i].day?.slice(0, 10) + 'T' + arr[6]?.[i].to),
    })
  }


    for (let i = 0; i < satData.length - 1; i++) {
      let findIndex = sat.findIndex(
        element =>
          element.startTime.getHours() +
            ':' +
            element.startTime.getMinutes() ===
          satData[i].startTime.getHours() + ':' + satData[i].startTime.getMinutes(),
      )
      if (findIndex > -1) {
        let secondIndex = satData.findIndex(
          element =>
            element.startTime.getHours() +
              ':' +
              element.startTime.getMinutes() ===
            sat[findIndex].endTime.getHours() +
              ':' +
              sat[findIndex].endTime.getMinutes(),
        )
        {
          satData.splice(i, secondIndex - i - 1)
        }
        satData[i] = sat[findIndex]
      }
    }
  
    for (let i = 0; i < sunData.length - 1; i++) {
      let findIndex = sun.findIndex(
        element =>
          element.startTime.getHours() +
            ':' +
            element.startTime.getMinutes() ===
          sunData[i].startTime.getHours() +
            ':' +
            sunData[i].startTime.getMinutes(),
      )
      if (findIndex > -1) {
        let secondIndex = sunData.findIndex(
          element =>
            element.startTime.getHours() +
              ':' +
              element.startTime.getMinutes() ===
            sun[findIndex].endTime.getHours() +
              ':' +
              sun[findIndex].endTime.getMinutes(),
        )
        {
          sunData.splice(i, secondIndex - i - 1)
        }
        sunData[i] = sun[findIndex]
      }
    }
  
    for (let i = 0; i < monData.length - 1; i++) {
      let findIndex = mon.findIndex(
        element =>
          element.startTime.getHours() +
            ':' +
            element?.startTime.getMinutes() ===
          monData[i].startTime.getHours() +
            ':' +
            monData[i].startTime.getMinutes(),
      )
      if (findIndex > -1) {
        let secondIndex = monData.findIndex(
          element =>
            element.startTime.getHours() +
              ':' +
              element.startTime.getMinutes() ===
            mon[findIndex].endTime.getHours() +
              ':' +
              mon[findIndex].endTime.getMinutes(),
        )
        {
          monData.splice(i, secondIndex - i - 1)
        }
        monData[i] = sat[findIndex]
      }
    }
  
    for (let i = 0; i < tueData.length - 1; i++) {
      let findIndex = tue.findIndex(
        element =>
          element.startTime.getHours() +
            ':' +
            element.startTime.getMinutes() ===
          tueData[i].startTime.getHours() +
            ':' +
            tueData[i].startTime.getMinutes(),
      )
      if (findIndex > -1) {
        let secondIndex = tueData.findIndex(
          element =>
            element.startTime.getHours() +
              ':' +
              element.startTime.getMinutes() ===
            tue[findIndex].endTime.getHours() +
              ':' +
              tue[findIndex].endTime.getMinutes(),
        )
        {
          tueData.splice(i, secondIndex - i - 1)
        }
        tueData[i] = tue[findIndex]
      }
    }
  
    for (let i = 0; i < wedData.length - 1; i++) {
      let findIndex = wed.findIndex(
        element =>
          element.startTime.getHours() +
            ':' +
            element.startTime.getMinutes() ===
          wedData[i].startTime.getHours() +
            ':' +
            wedData[i].startTime.getMinutes(),
      )
      if (findIndex > -1) {
        let secondIndex = wedData.findIndex(
          element =>
            element.startTime.getHours() +
              ':' +
              element.startTime.getMinutes() ===
            wed[findIndex].endTime.getHours() +
              ':' +
              wed[findIndex].endTime.getMinutes(),
        )
        {
          wedData.splice(i, secondIndex - i - 1)
        }
        wedData[i] = wed[findIndex]
      }
    }
  
 
    for (let i = 0; i < thuData.length - 1; i++) {
      let findIndex = thu.findIndex(
        element =>
          element.startTime.getHours() +
            ':' +
            element.startTime.getMinutes() ===
          thuData[i].startTime.getHours() +
            ':' +
            thuData[i].startTime.getMinutes(),
      )
      if (findIndex > -1) {
        let secondIndex = thuData.findIndex(
          element =>
            element.startTime.getHours() +
              ':' +
              element.startTime.getMinutes() ===
            thu[findIndex]?.endTime.getHours() +
              ':' +
              thu[findIndex]?.endTime.getMinutes(),
        )
        {
          thuData.splice(i, secondIndex - i - 1)
        }
        thuData[i] = thu[findIndex]
      }
    }
   
    for (let i = 0; i < friData.length - 1; i++) {
      let findIndex = fri.findIndex(
        element =>
          element.startTime.getHours() +
            ':' +
            element.startTime.getMinutes() ===
          friData[i].startTime.getHours() +
            ':' +
            friData[i].startTime.getMinutes(),
      )
      if (findIndex > -1) {
        let secondIndex = friData.findIndex(
          element =>
            element.startTime.getHours() +
              ':' +
              element.startTime.getMinutes() ===
            fri[findIndex].endTime.getHours() +
              ':' +
              fri[findIndex].endTime.getMinutes(),
        )
        {
          friData.splice(i, secondIndex - i - 1)
        }
        friData[i] = fri[findIndex]
      }
    }
  

  useEffect(() => {
    const start = {
      start: currentDate,
    }
    // weeklyMutaition.mutate({ body: start })
  }, [ currentDate])
  const handleYesterDay = () => {
    setCurrentDate(
      moment(showDay).locale('fa').subtract(7, 'day').format('YYYY/MM/DD'),
    )
  }
  const handleTomorrow = () => {
    setCurrentDate(
      moment(showDay).locale('fa').add(7, 'day').format('YYYY/MM/DD'),
    )
  }
 const isMobileDevice = useMediaQuery({
   query: '(max-width: 480px)'
 })
  return (
    <>
      <div className="flex justify-between w-[90%] mr-auto">
       <>{weeklyMutaition.isLoading || !showDay ? <div className={styles['skeleton-header']} />: <div className="text-steelBlue mt-3 font-bold text-[1.5em]">
          {moment(showDay).locale('fa').format('DD')}
          تا
          {moment(endDay).locale('fa').format('DD MMMM YYYY')}
        </div>}</>
        <div className="flex mt-3 sm:ml-[1.5em]">
          <MainButton
            icon="chevron-right"
            variant="icon"
            className="text-firewatch sm:text-[1.5em]"
            onClick={() => {
              handleYesterDay()
            }}
          />
          <MainButton
            variant="icon"
            icon="chevron-left"
            className="text-firewatch sm:text-[1.5em]"
            onClick={() => {
              handleTomorrow()
            }}
          />
        </div>
      </div>
      {/* <div className="flex w-[91.5%] mr-[5.6em] mt-2">
        {scheduleData?.items?.map(item => (
          <TableProgress
            bgcolor="#4182B4"
            portion={item.percent}
            portion_status={item.percent}
            opacity={1}
            dayName={item.dayName}
          />
        ))}
      </div> */}
      <div className="flex flex-row">
        <div className="w-full mt-[.8em] mx-2">
          <TimeTable
            events={{
              شنبه: satData,
              یکشنبه: sunData,
              دوشنبه: monData,
              'سه شنبه': tueData,
              'چهار شنبه': wedData,
              'پنج شنبه': thuData,
              جمعه: friData,
            }}
            style={{ height: isMobileDevice ? '3000px' : '2000px' }}
          />
        </div>
      </div>
    </>
  )
}

export default WeeklyContainer
